# Root logger
rootLogger.level=DEBUG
rootLogger.appenderRef.stdout.ref=stdout

# Console appender
appender.console.type=Console
appender.console.name=stdout
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n